### PR TITLE
Update chapter_1.md

### PR DESCRIPTION
**Pull request by DovePod**
Added some slang.

### CODE REVIEW

**Review by DovePod — COMMENTED** [review]
bri'ish

**Comment by CatFishing4Guyz** [comment]
Blimey, m8, bit much, innit?

**Comment by DovePod** [comment]
Naa bloke. So, want' so' wa'er?

**Comment by CatFishing4Guyz** [comment]
Aye, mate. Wanna eat biscuits and watch the telly?

**Comment by DovePod** [comment]
Brilliant idea chap!

**Review by typoes — APPROVED** [review]

**Comment by typoes** [comment]
Ta, mates. I'll just merge this, shall I?

**Comment by CatFishing4Guyz** [comment]
Marvelous! Splendid!

**Pull request merged**
